exclude: ^.*\b(alembic)\b.*$
repos:
  - repo: https://github.com/hadialqattan/pycln
    rev: v1.1.0
    hooks:
      - id: pycln
        args: ["-a"]
  - repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3
  - repo: local
    hooks:
      - id: jupyter-nb-clear-output
        name: jupyter-nb-clear-output
        files: \.ipynb$
        stages: [commit]
        language: system
        entry: jupyter nbconvert --ClearOutputPreprocessor.enabled=True --inplace
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.6.2
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier-plugin-svelte
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    # Ruff version.
    rev: "v0.0.206"
    hooks:
      - id: ruff
        # Respect `exclude` and `extend-exclude` settings.
        args: ["--force-exclude"]
  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.9.0
    hooks:
      - id: shellcheck
        # Optionally only show errors and warnings
        args: ["--severity=warning"]
  - repo: local
    hooks:
      - id: cargo-fmt
        name: fmt
        description: Format files with cargo fmt.
        entry: cargo +nightly fmt
        language: system
        types: [rust]
        pass_filenames: false
      - id: cargo-check
        name: cargo check
        description: Check the package for errors.
        entry: cargo check
        language: system
        types: [rust]
        pass_filenames: false
